USWDS-proposals: Add web-components directory
uswds/uswds-proposals pull request #18
Opened 2024-11-26 15:52 UTC by amyleadem

## Summary
Create a README and template for the web component pre-alphas.

2024-11-26 20:40 UTC, amyleadem commented on web-components/README.md
> +This directory is designed to capture decisions about the design and code structure of USWDS web components.
> [!note]
> I didn't use the name "Elements" here because I wasn't sure if we were cleared to use it. We can re-write if necessary.

2024-11-26 21:08 UTC, annepetersen commented on web-components/README.md
> +This directory is designed to capture decisions about the design and code structure of USWDS web components.
Pretty sure we're all set there, so I edited.

2024-11-26 21:08 UTC, annepetersen approved these changes
With the edits I made, looks good to me. But check my work too, y'all. 😅

2024-11-26 23:13 UTC, mahoneycm reviewed
A couple potential suggestions and questions! Nothing blocking.

2024-11-26 23:13 UTC, mahoneycm commented on web-components/README.md
**Question:** Does the rest of the proposals file structure make sense with this change? Should we create a core dir as well?

2024-11-26 23:13 UTC, mahoneycm commented on web-components/README.md
> +1. Create a branch for the web component pre-alpha using the following naming structure: `[component-name]-pre-alpha`
**Question:** Should we prefix the PRs with our initials?

```suggestion
1. Create a branch for the web component pre-alpha using the following naming structure: `[initials]-[component-name]-pre-alpha`
```

2024-11-26 23:13 UTC, mahoneycm commented on web-components/_template.md
> +  https://drive.google.com/drive/folders/1F8z7v5RCOV3D33iEz7TR0B8IHv20WNMF
**Question:** Should we make a note that this link is internal only? 

I know we have the note that only the core team can make the proposals for now but I'm curious if we should make note in case anyone is poking around the files.

Might not be important!

2024-11-26 23:13 UTC, mahoneycm commented on web-components/_template.md
> +| |  |  |
Minor formatting:

```suggestion
|  |  |  |
```

2024-11-26 23:13 UTC, mahoneycm commented on web-components/_template.md
> +-->
**Question:** Not sure I follow what the the `Web components variant` is supposed to be listed as here. 

Is this just the name of the variant? Would this differ from the USWDS 3 variant?

2024-11-26 23:13 UTC, mahoneycm commented on web-components/_template.md
> +| -- |  |  |  |
**Suggestion (non-blocking):** Personally, I like the hyphens here in between the columns. It feels a bit easier to distinguish the column spaces and dividers.

```suggestion
| USWDS 3 variant | Web components variant | Description | Defined via |
|--------|--------|--------|--------|
| -- | -- | -- | -- |
```

Curious what others think/prefer!

2024-11-27 14:29 UTC, heymatthenry commented on web-components/_template.md
> +| -- |  |  |  |
Agree re: hyphens and that it shouldn't be a blocker. Ideally the columns would be the same width and depending on your editor there should be away to do that automagically, but it's also probably not worth spending any actual time to make that happen

2024-11-27 17:23 UTC, amyleadem commented on web-components/_template.md
> +| -- |  |  |  |
Good notes. Automagicked the formatting in VS code. Let me know if you want any other changes to the table formatting.

2024-11-27 18:16 UTC, amyleadem commented on web-components/README.md
This is a good note. The repo was originally designed to just be for component proposals, and I think the recent repo growth is showing strangely in both the file structure and base README. Now that the repo will also include ADRs and Elements pre-alphas, we should at least address that in the README and consider if the file structure still makes sense. I've opened https://github.com/uswds/uswds-proposals/issues/19 to address the README piece of this.

2024-11-27 21:08 UTC, annepetersen commented
_Completely_ a content item, but I'd love to discontinue using "here's the" or "here you can find" in any lead on any page. In most cases it can just be dropped and the sentence still works. 

Copying @finekatie to maybe add this to the voice/tone/guide discussion.

2024-12-03 15:57 UTC, mejiaj reviewed
Thanks for creating this @amyleadem. Overall it looks good. Left a few comments, but nothing is blocking.

I've also made some formatting changes using the built-in markdown formatter in Prettier.

2024-12-03 15:57 UTC, mejiaj commented on web-components/README.md
> +1. Create a branch for the web component pre-alpha using the following naming structure: `[component-name]-pre-alpha`
That's a good point @mahoneycm. Do you see any issues with not having initials?

We do this with code to avoid collision in branch names when we're working on the same feature. 

It's doubtful that two of us would be working on the same pre-alpha document. Although it can happen if we want to make significant changes via a PR.

2024-12-03 15:57 UTC, mejiaj commented on web-components/_template.md
> +_In a table, list the component content that is critical for user understanding. These elements should always be painted on the page, even when JavaScript is unavailable or slow._
**polish**: Small suggestion to  remove the word `painted` because it might be too technical.

```suggestion
_In a table, list the component content that is critical for user understanding. These elements should always be on the page, even when JavaScript is unavailable or slow._
```

2024-12-03 15:57 UTC, mejiaj commented on web-components/_template.md
> +_Provide a code sample for the web component in the light DOM. Provide default and complex implementations when applicable._
**polish**: The heading already mentions light DOM. We can use plain language for the requirements.

```suggestion
_Provide an example for how the web component would be used. Include a default example and complex example (when applicable)._
```

2024-12-03 15:57 UTC, mejiaj commented on web-components/_template.md
> +```html
**polish**: We could add clarity by adding an HTML comment marking that this is the shadow DOM markup.

```suggestion
```html
<!-- #shadow-root -->

```

2024-12-10 16:22 UTC, amyleadem commented on web-components/_template.md
> +[Component] code samples from the landscape analysis (Google docs :lock:)
Yes, I don't think we need to do a full analysis of each components. It feels more appropriate to just grab code samples for comparison.

2024-12-10 16:33 UTC, amyleadem commented on web-components/README.md
> +1. Create a branch for the web component pre-alpha using the following naming structure: `[component-name]-pre-alpha`
I updated the recommended branch structure to `[contributor initials]-pre-alpha-[component-name]` in https://github.com/uswds/uswds-proposals/pull/18/commits/2e1e23f01e2e5155e1d94e5a85554e78859f292d.

Let me know if you have any objections or concerns.

2024-12-10 16:42 UTC, amyleadem commented on web-components/_template.md
> +```html
Good idea. Added in [5020a85](https://github.com/uswds/uswds-proposals/pull/18/commits/5020a85e4ee0faf82ae8efe3e58159af8177c3ec)

2024-12-10 16:43 UTC, amyleadem commented on web-components/_template.md
> +_Provide a code sample for the web component in the light DOM. Provide default and complex implementations when applicable._
Updated the copy to "_Provide a code sample of how a user would add this web component to their project. Provide a default example and a complex example (when applicable)._"  in [5020a85](https://github.com/uswds/uswds-proposals/pull/18/commits/5020a85e4ee0faf82ae8efe3e58159af8177c3ec)

2024-12-10 16:43 UTC, amyleadem commented on web-components/_template.md
> +_In a table, list the component content that is critical for user understanding. These elements should always be painted on the page, even when JavaScript is unavailable or slow._
Updated in [5020a85](https://github.com/uswds/uswds-proposals/pull/18/commits/5020a85e4ee0faf82ae8efe3e58159af8177c3ec)

2024-12-10 16:45 UTC, amyleadem commented on web-components/_template.md
> +| USWDS 3 variant | Web components variant | Description | Defined via |
It was intended to capture how the user would set this variant in the light DOM.

Since I imagine this would almost always be a prop of some sort, I updated the heading to "Related prop" in [5020a85](https://github.com/uswds/uswds-proposals/pull/18/commits/5020a85e4ee0faf82ae8efe3e58159af8177c3ec). 

Let me know if that is still unclear.

2024-12-10 16:46 UTC, amyleadem commented on web-components/_template.md
> +| |  |  |
Formatted tables in [3911ae9](https://github.com/uswds/uswds-proposals/pull/18/commits/3911ae91fb05b2fb7d03592d12d5b76196324c2b)

2024-12-10 16:47 UTC, amyleadem commented on web-components/_template.md
> +  https://drive.google.com/drive/folders/1F8z7v5RCOV3D33iEz7TR0B8IHv20WNMF
I added a "limited access" note in [5020a85](https://github.com/uswds/uswds-proposals/pull/18/commits/5020a85e4ee0faf82ae8efe3e58159af8177c3ec).

2025-02-10 17:03 UTC, mejiaj requested changes
@amyleadem can you look into the formatting issue? We might have to move some code blocks out of comments. 

Otherwise LGTM

2025-02-10 17:03 UTC, mejiaj commented on web-components/_template.md
@amyleadem can you look into display issues showing up in the preview?

https://github.com/uswds/uswds-proposals/blob/5020a85e4ee0faf82ae8efe3e58159af8177c3ec/web-components/_template.md

![capture-Arc-2025-02-10@2x](https://github.com/user-attachments/assets/864a182f-9568-460e-9f67-6d8343fffad4)

2025-03-19 16:17 UTC, amycole501 commented
Not planned

2025-03-19 16:17 UTC, closed without merging